# Generated by Django 3.0.7 on 2020-07-21 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('OMIM_id', models.CharField(blank=True, max_length=20)),
                ('Ensembl_id', models.CharField(blank=True, max_length=20)),
                ('infos', models.TextField(blank=True, verbose_name='Other information')),
            ],
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('associated_gene_OMIM', models.CharField(max_length=20)),
                ('infos', models.TextField(blank=True, verbose_name='Other information')),
            ],
            options={
                'verbose_name': 'Pathologie',
            },
        ),
        migrations.CreateModel(
            name='variantsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('path_file', models.CharField(max_length=200)),
                ('real_path_file', models.FilePathField(path='/home/maelle/Bureau/Stage/Data')),
                ('tab', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('real_path_file', models.FilePathField(path='/home/maelle/Bureau/Stage/Data')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('running', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
