# Generated by Django 3.0.7 on 2020-07-30 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('OMIM_id', models.CharField(blank=True, max_length=20)),
                ('Ensembl_id', models.CharField(blank=True, max_length=20)),
                ('infos', models.TextField(blank=True, verbose_name='Other information')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('associated_gene_OMIM', models.CharField(max_length=20)),
                ('infos', models.TextField(blank=True, verbose_name='Other information')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Pathologies',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField(blank=True)),
                ('age', models.SmallIntegerField()),
                ('age_of_unset', models.SmallIntegerField()),
                ('infos', models.TextField(blank=True, verbose_name='Other information')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('pathology', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='variantsViz.Pathology')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('real_path_file', models.FilePathField(path='/home/maelle/Bureau/Stage/Data')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('running', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
