# Generated by Django 3.0.7 on 2020-07-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='creation_date',
        ),
    ]
