# Generated by Django 3.0.7 on 2020-07-30 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0002_auto_20200730_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='pathology',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
