# Generated by Django 3.0.7 on 2020-06-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0002_auto_20200619_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='tab',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
