# Generated by Django 3.0.7 on 2020-07-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0003_auto_20200730_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='creation_date',
            new_name='initialisation_date',
        ),
        migrations.RenameField(
            model_name='pathology',
            old_name='creation_date',
            new_name='initialisation_date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='creation_date',
            new_name='initialisation_date',
        ),
    ]
