# Generated by Django 3.0.7 on 2020-07-31 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0004_auto_20200730_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='OMIM_id',
            new_name='Entrez_id',
        ),
        migrations.AddField(
            model_name='gene',
            name='MIM_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_id', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('ACMG_diagnostic', models.CharField(blank=True, max_length=20)),
                ('manual_diagnostic', models.BooleanField(blank=True, default=False)),
                ('AAchange', models.CharField(blank=True, max_length=20)),
                ('infos', models.TextField(blank=True, verbose_name='Other information')),
                ('clinvar_link', models.CharField(blank=True, max_length=200)),
                ('orphadata_link', models.CharField(blank=True, max_length=200)),
                ('CADD_score', models.CharField(blank=True, max_length=200)),
                ('Polyphen_score', models.CharField(blank=True, max_length=200)),
                ('MutationTaster_score', models.CharField(blank=True, max_length=200)),
                ('initialisation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('associated_pathology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variantsViz.Pathology')),
                ('gene', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='variantsViz.Gene')),
            ],
        ),
    ]
