# Generated by Django 3.0.7 on 2020-07-31 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0005_auto_20200731_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='associated_pathology',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='variantsViz.Pathology'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='manual_diagnostic',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
