# Generated by Django 3.0.7 on 2020-06-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0005_auto_20200624_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='reaal_path_file',
            field=models.FilePathField(default='def', path='/home/maelle/Bureau/Stage/tabResult.csv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='running',
            field=models.BooleanField(default=True),
        ),
    ]
