# Generated by Django 3.0.7 on 2020-08-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0006_auto_20200731_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='associated_pathology',
        ),
        migrations.AddField(
            model_name='gene',
            name='associated_pathologies',
            field=models.ManyToManyField(blank=True, to='variantsViz.Pathology'),
        ),
        migrations.AddField(
            model_name='variant',
            name='associated_pathologies',
            field=models.ManyToManyField(blank=True, to='variantsViz.Pathology'),
        ),
    ]
