# Generated by Django 3.0.7 on 2020-08-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0007_auto_20200801_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age_of_unset',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
