# Generated by Django 3.0.7 on 2020-06-30 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('variantsViz', '0007_auto_20200630_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='running',
        ),
        migrations.AlterField(
            model_name='table',
            name='real_path_file',
            field=models.FilePathField(path='/home/maelle/Bureau/Stage/Data'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('real_path_file', models.FilePathField(path='/home/maelle/Bureau/Stage/Data')),
                ('text', models.TextField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('running', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
