# Generated by Django 3.0.7 on 2020-06-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0008_auto_20200630_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created_date',
            new_name='start_date',
        ),
    ]
