# Generated by Django 3.0.7 on 2020-08-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0008_auto_20200803_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[(' ', 'Unknown'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
