# Generated by Django 3.0.7 on 2020-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0009_auto_20200803_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathology',
            name='associated_gene_OMIM',
        ),
        migrations.AddField(
            model_name='pathology',
            name='associated_gene_OMIM',
            field=models.ManyToManyField(blank=True, to='variantsViz.Gene'),
        ),
    ]
