# Generated by Django 3.0.7 on 2020-08-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0010_auto_20200804_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
