# Generated by Django 3.0.7 on 2020-08-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0011_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathology',
            name='associated_gene_OMIM',
        ),
        migrations.AddField(
            model_name='pathology',
            name='associated_gene_OMIM',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
