# Generated by Django 3.0.7 on 2020-08-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0012_auto_20200813_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathology',
            name='associated_gene_OMIM',
        ),
        migrations.AddField(
            model_name='pathology',
            name='associated_genes',
            field=models.ManyToManyField(blank=True, to='variantsViz.Gene'),
        ),
    ]
