# Generated by Django 3.0.7 on 2020-08-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variantsViz', '0013_auto_20200830_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='Entrez_id',
        ),
    ]
